site_name: My Materials
site_description: Notes and recipes
site_url: https://behealthy92.github.io/recipes/
repo_url: https://github.com/behealthy92/recipes
repo_name: behealthy92/recipes

nav:
  - Home: index.md
  - Recipes:
      - README: recipes/index.md
      - Frozen Triple Berry Smoothie: recipes/frozen-triple-berry-smoothie.md

theme:
  name: mkdocs

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
